version: "3.3"
services:
  sonic:
    image: "valeriansaliou/sonic:v1.4.3"
    container_name: "sonic"
    ports:
      - "1491:1491"
    volumes:
      - "./config/sonic.cfg:/etc/sonic.cfg"
      - "./store/:/var/lib/sonic/store/"
